### ISSUE TITLE
Missing hover effect on .primary-toolbar button (outside of maybe Nemo)

### ISSUE THREAD

**Issue by AndreiMiculita** [EliverLara/Sweet#133]
Hi, there are some widgets that show their default style when hovered over with this theme. In Linux Mint, for example, they are at the top of the theme selection windows (see screenshots), as well as in other system settings.

![Screenshot from 2021-01-19 18-20-25](https://user-images.githubusercontent.com/6352172/105070579-cbb84980-5a83-11eb-9438-0d3edad0ad0a.png)
![Screenshot from 2021-01-19 18-20-38](https://user-images.githubusercontent.com/6352172/105070581-cc50e000-5a83-11eb-83a7-eb5e7d611e17.png)

I assume this is not how it's meant to look.

I've managed to find their selector: `.primary-toolbar button`. I noticed it is defined for nemo windows (I think?) 
```css
.nemo-window toolbar.primary-toolbar button:hover {
    color: #F67E7D;
}
``` 

After defining the style for hovering like this:
```css
.primary-toolbar button:hover,
.primary-toolbar button:focus,
.primary-toolbar .raised button:hover,
.primary-toolbar .raised button:focus {
    color: #F67E7D;
}
```
in `gtk-3.0/gtk.css`
This is how they look:
![Screenshot from 2021-01-19 18-19-22](https://user-images.githubusercontent.com/6352172/105070577-ca871c80-5a83-11eb-8c27-633a91ae93e1.png)
![Screenshot from 2021-01-19 18-19-41](https://user-images.githubusercontent.com/6352172/105070578-cb1fb300-5a83-11eb-827e-cf2db993b2ea.png)
Not sure what your preference is, but if you want to fix it, you have the selectors you might need.
